name: radiostring
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bloc: ^4.0.0
  http: ^0.12.1
  connectivity: ^0.4.8+6
  rxdart: ^0.24.1
  flutter_svg: ^0.18.0
  flushbar: ^1.10.4
  shared_preferences: ^0.5.8
  url_audio_stream: ^1.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/favourite.png
    - assets/images/filters.svg
    - assets/images/play-button.svg
    - assets/images/search.svg
    - assets/images/sidebar.png
    - assets/images/squares.png
    - assets/images/unfavourite.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/twitter.png

  fonts:
    - family: 'Jost-Light'
      fonts:
        - asset: assets/fonts/Jost-Light.ttf
          weight: 300
    - family: 'Jost-Regular'
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
    - family: 'Jost-Medium'
      fonts:
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
